In [1]:
import pandas as pd
import numpy as np
import math
from imblearn.over_sampling import KMeansSMOTE
from imblearn.over_sampling import SMOTE
from sklearn.cluster import KMeans

In [2]:
# Load dataset
Data_2017 = pd.read_csv("..\\Data\\old\\17_final.csv", delimiter=',')
Data_2018 = pd.read_csv("..\\Data\\old\\18_final.csv", delimiter=',')
Data_2019 = pd.read_csv("..\\Data\\old\\19_final.csv", delimiter=',')
datas = [Data_2017 , Data_2018, Data_2019]


# Check imbalance


In [3]:
# Observe class imbalance
print(sum(Data_2017.label == 1))
print(sum(Data_2017.label == 0))
print(sum(Data_2017.label == 1)/len(Data_2017))
print(sum(Data_2017.label == 0)/len(Data_2017))

# Observe class imbalance
print(sum(Data_2018.label == 1))
print(sum(Data_2018.label == 0))
print(sum(Data_2018.label == 1)/len(Data_2018))
print(sum(Data_2018.label == 0)/len(Data_2018))

# Observe class imbalance
print(sum(Data_2019.label == 1))
print(sum(Data_2019.label == 0))
print(sum(Data_2019.label == 1)/len(Data_2019))
print(sum(Data_2019.label == 0)/len(Data_2019))

6382
362633
0.01729468991775402
0.9827053100822459
6892
363696
0.018597472125379128
0.9814025278746209
5535
366545
0.014875833154160396
0.9851241668458396


In [4]:
# Split data in X and y
def X_Y(train, labelss):
    X_train = train.drop(labels=labelss, axis=1)
    X_train = X_train.to_numpy()
    y_train = train["label"].to_numpy()
    return X_train, y_train

In [5]:
# Try KMeans on the different datasets
n = 5
results = []
kmeans = KMeans(init="k-means++", n_clusters=n, n_init=30, max_iter=800)
labels = ["c28992r100", "AANTAL_HH","GEM_HH_GR","P_HUURWON","P_KOOPWON", "G_ELEK_WON", 'WON_NBEW',
          "G_GAS_WON", "WOZWONING", "woon","winkel","gezondheid","kantoor","bijeenkomst",
          "onderwijs","sport","industrie","logies","min_construction_year","max_construction_year","mean_construction_year",
          "P_HINK_HH","P_LINK_HH", "UITKMINAOW", "sur_green","sur_water","sur_road","sur_other",
         "Fundering",'INW_014', 'INW_1524', 'INW_2544', 'INW_4564', 'INW_65PL']

for data in datas:
    X, y = X_Y(data, labels)
    result = kmeans.fit_predict(X,y)
    results.append(result)
    data["cluster"] = result
    print(result)
    for i in range(0,n):
        filtr = data[(data.cluster == i)]
        print("Cluster " + str(i))
        print("Negative:",(len(filtr) - sum(filtr.label)))
        print("Positive:", " ", sum(filtr.label))
        print("--------")


[3 3 3 ... 2 2 2]
Cluster 0
Negative: 71205
Positive:   1160
--------
Cluster 1
Negative: 76765
Positive:   1441
--------
Cluster 2
Negative: 74547
Positive:   1216
--------
Cluster 3
Negative: 58470
Positive:   850
--------
Cluster 4
Negative: 81646
Positive:   1715
--------
[4 4 4 ... 2 2 2]
Cluster 0
Negative: 71464
Positive:   1292
--------
Cluster 1
Negative: 77040
Positive:   1545
--------
Cluster 2
Negative: 74647
Positive:   1313
--------
Cluster 3
Negative: 81909
Positive:   1840
--------
Cluster 4
Negative: 58636
Positive:   902
--------
[2 2 2 ... 3 3 3]
Cluster 0
Negative: 71732
Positive:   1245
--------
Cluster 1
Negative: 77549
Positive:   1220
--------
Cluster 2
Negative: 58832
Positive:   920
--------
Cluster 3
Negative: 76005
Positive:   276
--------
Cluster 4
Negative: 82427
Positive:   1874
--------


In [6]:
qgis_train = pd.DataFrame(Data_2017["c28992r100"],columns=["c28992r100"])
qgis_test = pd.DataFrame(Data_2018["c28992r100"],columns=["c28992r100"])
qgis_val = pd.DataFrame(Data_2019["c28992r100"],columns=["c28992r100"])
qgis_train["cluster"] = results[0]
qgis_test["cluster"] = results[1]
qgis_val["cluster"] = results[2]

qgis_train.to_csv("qgistrainno.csv", index=False)
qgis_test.to_csv("qgistestno.csv", index=False)
qgis_val.to_csv("qgisvalno.csv", index=False)

In [7]:
# Try KMeans on the different datasets
n = 5
results = []
kmeans = KMeans(init="k-means++", n_clusters=n, n_init=30, max_iter=800)
labels = ["c28992r100", "AANTAL_HH","GEM_HH_GR","P_HUURWON","P_KOOPWON", "G_ELEK_WON", 'WON_NBEW',
          "G_GAS_WON", "WOZWONING", "woon","winkel","gezondheid","kantoor","bijeenkomst",
          "onderwijs","sport","industrie","logies","min_construction_year","max_construction_year","mean_construction_year",
          "P_HINK_HH","P_LINK_HH", "UITKMINAOW", "sur_green","sur_water","sur_road","sur_other",
         "Fundering",'INW_014', 'INW_1524', 'INW_2544', 'INW_4564', 'INW_65PL', "row", "column"]

for data in datas:
    X, y = X_Y(data, labels)
    result = kmeans.fit_predict(X,y)
    results.append(result)
    data["cluster"] = result
    print(result)
    for i in range(0,n):
        filtr = data[(data.cluster == i)]
        print("Cluster " + str(i))
        print("Negative:",(len(filtr) - sum(filtr.label)))
        print("Positive:", " ", sum(filtr.label))
        print("--------")

qgis_train = pd.DataFrame(Data_2017["c28992r100"],columns=["c28992r100"])
qgis_test = pd.DataFrame(Data_2018["c28992r100"],columns=["c28992r100"])
qgis_val = pd.DataFrame(Data_2019["c28992r100"],columns=["c28992r100"])
qgis_train["cluster"] = results[0]
qgis_test["cluster"] = results[1]
qgis_val["cluster"] = results[2]

qgis_train.to_csv("qgistrain.csv", index=False)
qgis_test.to_csv("qgistest.csv", index=False)
qgis_val.to_csv("qgisval.csv", index=False)

[1 1 1 ... 1 1 1]
Cluster 0
Negative: 17899
Positive:   538
--------
Cluster 1
Negative: 176664
Positive:   2808
--------
Cluster 2
Negative: 101242
Positive:   1882
--------
Cluster 3
Negative: 3645
Positive:   162
--------
Cluster 4
Negative: 63183
Positive:   992
--------
[0 0 0 ... 0 0 0]
Cluster 0
Negative: 176629
Positive:   3019
--------
Cluster 1
Negative: 102119
Positive:   2069
--------
Cluster 2
Negative: 18108
Positive:   594
--------
Cluster 3
Negative: 3650
Positive:   192
--------
Cluster 4
Negative: 63190
Positive:   1018
--------
[0 0 0 ... 0 0 0]
Cluster 0
Negative: 177938
Positive:   2266
--------
Cluster 1
Negative: 18037
Positive:   559
--------
Cluster 2
Negative: 103141
Positive:   1663
--------
Cluster 3
Negative: 3562
Positive:   204
--------
Cluster 4
Negative: 63867
Positive:   843
--------


In [9]:
# Try KMeans on the different datasets
n = 5
results = []
kmeans = KMeans(init="k-means++", n_clusters=n, n_init=30, max_iter=800)
labels = ["c28992r100", "AANTAL_HH","GEM_HH_GR","P_HUURWON","P_KOOPWON", "G_ELEK_WON", 'WON_NBEW',
          "G_GAS_WON", "WOZWONING", "woon","winkel","gezondheid","kantoor","bijeenkomst",
          "onderwijs","sport","industrie","logies","min_construction_year","max_construction_year","mean_construction_year",
          "P_HINK_HH","P_LINK_HH", "UITKMINAOW",
         "Fundering",'INW_014', 'INW_1524', 'INW_2544', 'INW_4564', 'INW_65PL', "row", "column"]

for data in datas:
    X, y = X_Y(data, labels)
    result = kmeans.fit_predict(X,y)
    results.append(result)
    data["cluster"] = result
    print(result)
    for i in range(0,n):
        filtr = data[(data.cluster == i)]
        print("Cluster " + str(i))
        print("Negative:",(len(filtr) - sum(filtr.label)))
        print("Positive:", " ", sum(filtr.label))
        print("--------")

qgis_train = pd.DataFrame(Data_2017["c28992r100"],columns=["c28992r100"])
qgis_test = pd.DataFrame(Data_2018["c28992r100"],columns=["c28992r100"])
qgis_val = pd.DataFrame(Data_2019["c28992r100"],columns=["c28992r100"])
qgis_train["cluster"] = results[0]
qgis_test["cluster"] = results[1]
qgis_val["cluster"] = results[2]

qgis_train.to_csv("qgistrain2.csv", index=False)
qgis_test.to_csv("qgistest2.csv", index=False)
qgis_val.to_csv("qgisval2.csv", index=False)

[1 0 0 ... 4 4 4]
Cluster 0
Negative: 316756
Positive:   6129
--------
Cluster 1
Negative: 10035
Positive:   57
--------
Cluster 2
Negative: 9
Positive:   0
--------
Cluster 3
Negative: 1479
Positive:   4
--------
Cluster 4
Negative: 34354
Positive:   192
--------
[1 0 0 ... 2 2 2]
Cluster 0
Negative: 316689
Positive:   6613
--------
Cluster 1
Negative: 10352
Positive:   47
--------
Cluster 2
Negative: 35183
Positive:   227
--------
Cluster 3
Negative: 9
Positive:   0
--------
Cluster 4
Negative: 1463
Positive:   5
--------
[0 3 3 ... 3 3 0]
Cluster 0
Negative: 35082
Positive:   163
--------
Cluster 1
Negative: 167
Positive:   0
--------
Cluster 2
Negative: 7160
Positive:   24
--------
Cluster 3
Negative: 324128
Positive:   5348
--------
Cluster 4
Negative: 8
Positive:   0
--------


In [10]:
# Try KMeans on the different datasets
n = 5
results = []
kmeans = KMeans(init="k-means++", n_clusters=n, n_init=30, max_iter=800)
labels = ["c28992r100", "AANTAL_HH","GEM_HH_GR","P_HUURWON","P_KOOPWON", "G_ELEK_WON", 'WON_NBEW',
          "G_GAS_WON", "WOZWONING","min_construction_year","max_construction_year","mean_construction_year",
          "P_HINK_HH","P_LINK_HH", "UITKMINAOW", "sur_green","sur_water","sur_road","sur_other",
         "Fundering",'INW_014', 'INW_1524', 'INW_2544', 'INW_4564', 'INW_65PL', "row", "column"]

for data in datas:
    X, y = X_Y(data, labels)
    result = kmeans.fit_predict(X,y)
    results.append(result)
    data["cluster"] = result
    print(result)
    for i in range(0,n):
        filtr = data[(data.cluster == i)]
        print("Cluster " + str(i))
        print("Negative:",(len(filtr) - sum(filtr.label)))
        print("Positive:", " ", sum(filtr.label))
        print("--------")

qgis_train = pd.DataFrame(Data_2017["c28992r100"],columns=["c28992r100"])
qgis_test = pd.DataFrame(Data_2018["c28992r100"],columns=["c28992r100"])
qgis_val = pd.DataFrame(Data_2019["c28992r100"],columns=["c28992r100"])
qgis_train["cluster"] = results[0]
qgis_test["cluster"] = results[1]
qgis_val["cluster"] = results[2]

qgis_train.to_csv("qgistrain3.csv", index=False)
qgis_test.to_csv("qgistest3.csv", index=False)
qgis_val.to_csv("qgisval3.csv", index=False)

[0 0 0 ... 0 0 0]
Cluster 0
Negative: 175927
Positive:   2657
--------
Cluster 1
Negative: 62664
Positive:   1021
--------
Cluster 2
Negative: 3646
Positive:   170
--------
Cluster 3
Negative: 103585
Positive:   1967
--------
Cluster 4
Negative: 16811
Positive:   567
--------
[1 1 1 ... 1 1 1]
Cluster 0
Negative: 104605
Positive:   2165
--------
Cluster 1
Negative: 176202
Positive:   2855
--------
Cluster 2
Negative: 3503
Positive:   193
--------
Cluster 3
Negative: 62880
Positive:   1072
--------
Cluster 4
Negative: 16506
Positive:   607
--------
[1 1 1 ... 1 1 1]
Cluster 0
Negative: 16513
Positive:   578
--------
Cluster 1
Negative: 177242
Positive:   2115
--------
Cluster 2
Negative: 105871
Positive:   1755
--------
Cluster 3
Negative: 3527
Positive:   208
--------
Cluster 4
Negative: 63392
Positive:   879
--------


In [12]:
# Try KMeans on the different datasets
n = 5
results = []
kmeans = KMeans(init="k-means++", n_clusters=n, n_init=30, max_iter=800)
labels = ["c28992r100", "sur_green","sur_water","sur_road","sur_other", "row", "column"]

for data in datas:
    X, y = X_Y(data, labels)
    result = kmeans.fit_predict(X,y)
    results.append(result)
    data["cluster"] = result
    print(result)
    for i in range(0,n):
        filtr = data[(data.cluster == i)]
        print("Cluster " + str(i))
        print("Negative:",(len(filtr) - sum(filtr.label)))
        print("Positive:", " ", sum(filtr.label))
        print("--------")

qgis_train = pd.DataFrame(Data_2017["c28992r100"],columns=["c28992r100"])
qgis_test = pd.DataFrame(Data_2018["c28992r100"],columns=["c28992r100"])
qgis_val = pd.DataFrame(Data_2019["c28992r100"],columns=["c28992r100"])
qgis_train["cluster"] = results[0]
qgis_test["cluster"] = results[1]
qgis_val["cluster"] = results[2]

qgis_train.to_csv("qgistrain4.csv", index=False)
qgis_test.to_csv("qgistest4.csv", index=False)
qgis_val.to_csv("qgisval4.csv", index=False)

[3 3 3 ... 2 2 2]
Cluster 0
Negative: 71920
Positive:   2231
--------
Cluster 1
Negative: 43019
Positive:   1096
--------
Cluster 2
Negative: 109628
Positive:   1108
--------
Cluster 3
Negative: 112125
Positive:   1638
--------
Cluster 4
Negative: 25941
Positive:   309
--------
[0 0 0 ... 1 1 1]
Cluster 0
Negative: 112259
Positive:   1724
--------
Cluster 1
Negative: 100030
Positive:   1205
--------
Cluster 2
Negative: 75993
Positive:   2522
--------
Cluster 3
Negative: 24443
Positive:   323
--------
Cluster 4
Negative: 50971
Positive:   1118
--------
[0 0 0 ... 0 1 1]
Cluster 0
Negative: 136724
Positive:   2018
--------
Cluster 1
Negative: 116319
Positive:   985
--------
Cluster 2
Negative: 77799
Positive:   2006
--------
Cluster 3
Negative: 25378
Positive:   252
--------
Cluster 4
Negative: 10325
Positive:   274
--------


In [ ]:
# Do SMOTE separately
samples = []
labels = ["c28992r100","label"]

data = datas[0]
X, y = X_Y(data,labels)
smote = SMOTE(k_neighbors=10, sampling_strategy=1.)
X_res, y_res = smote.fit_resample(X, y)
samples.append([X_res, y_res])
print(np.count_nonzero(y_res == 0))
print(np.count_nonzero(y_res == 1))
print(smote.get_params())

data = datas[1]
X, y = X_Y(data,labels)
smote = SMOTE(k_neighbors=10, sampling_strategy=1.0)
X_res, y_res = smote.fit_resample(X, y)
samples.append([X_res, y_res])
print(np.count_nonzero(y_res == 0))
print(np.count_nonzero(y_res == 1))
print(smote.get_params())

data = datas[2]
X, y = X_Y(data,labels)
smote = SMOTE(k_neighbors=10, sampling_strategy=1.0)
X_res, y_res = smote.fit_resample(X, y)
samples.append([X_res, y_res])
print(np.count_nonzero(y_res == 0))
print(np.count_nonzero(y_res == 1))
print(smote.get_params())

# Reshape results
feature_columns = []
for sa in samples:
    new = np.reshape(sa[0], (len(sa[0]), len(sa[0][0]))).T
    print(new)
    print(len(new))
    feature_columns.append([new,sa[1]])
    print("---------")